### ISSUE TITLE
run Ombi in freebsd

### ISSUE THREAD

**Issue by ClappTV** [Thefrank/dotnet-freebsd-native-binaries#1]
thanks for all the work done.
I am looking to install Ombi in a Freebsd jail, would there be any possibility to make a package like jellyfin for Ombi?
Thanks!

PD: https://github.com/Ombi-app/Ombi

**Comment by Thefrank** [comment]
I already have a tarball in https://github.com/Thefrank/freebsd-port-sooners (it is pretty old at this point). You can bug me again over there when the dev moves to dotnet6 and ill take a look again ;)

It has some pretty big issues that prevent it from being used in a service.  I think that is because `self-contained` + `singlefile` does not work correctly under dotNET5 with FreeBSD. These may have been resolved in dotNET6 but I have not had the time to dig into it.

**Comment by Thefrank** [comment]
See here: https://github.com/Thefrank/freebsd-port-sooners/issues/11
